### ISSUE TITLE
Mobile or tablet support?

### ISSUE THREAD

**Issue by Cookizza** [SeanJM/parallax#1]
Any chance of hooking this up to tablets or mobile?

**Comment by SeanJM** [comment]
My Skype is seanmacisaac, you can give me a call and walk me through the problem. I'll try and help you out!

**Comment by SeanJM** [comment]
I deleted the local repository today, it's funny that you closed your comment.

**Comment by Cookizza** [comment]
Aha must have been a feeling in the world yesterday.

This was a great help in us writing our own internal parallax library, so
thanks for all your contributions to parallax way back when nobody was
doing it right.

Cheers!
